version = 1

[[annotations]]
path = [".node-version", "pnpm-lock.yaml"]
SPDX-FileCopyrightText = "2025 Ryan Cao <hello@ryanccn.dev>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["package.json", "tsconfig.json", "tsconfigs/*.json"]
SPDX-FileCopyrightText = "2025 Ryan Cao <hello@ryanccn.dev>"
SPDX-License-Identifier = "AGPL-3.0-or-later"
